{% set name = "scikit-fda" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-fda-{{ version }}.tar.gz
  sha256: dccb7b2dd8f324849fcfde1a17e35801f621d9cb05d7d0247c731a9561f33305

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dcor
    - fdasrsf >=2.2.0
    - findiff
    - lazy_loader
    - matplotlib-base
    - multimethod >=1.5
    - numpy >=1.16
    - pandas >=1.0
    - python >=3.8
    - rdata
    - scikit-datasets >=0.1.24
    - scikit-learn >=0.20
    - scipy >=1.3.0
    - typing-extensions

test:
  imports:
    - skfda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scikit-fda/
  summary: Functional Data Analysis Python package.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - vnmabus
